---
  - name: Create django postgres user
    postgresql_user: name={{ db_user }} password={{ db_password }}
    become_user: postgres

  - name: Create postgres database
    postgresql_db:
      name={{ db_name }}
      owner={{ db_user }}
      encoding='UTF-8'
      lc_collate={{ db_locale }}
      lc_ctype={{ db_locale }}
      template='template1'
    become_user: postgres
    run_once: true

  - name: Grant database rights to app user
    postgresql_privs: >
      db=postgres
      state=present
      privs=ALL
      type=database
      obj={{ db_name }}
      role={{ db_user }}
    become_user: postgres
