dist: xenial

language: python
cache: pip

python:
  - "3.5"

env:
  - LINT="yes"
  - DJANGO="2.1"
  global:
  - PGPORT=5433


matrix:
  exclude:
  - python: "3.5"
    env: LINT="yes"

addons:
  postgresql: "10"
  apt:
    packages:
      - libjpeg8
      - libjpeg8-dev
      - postgresql-10
      - postgresql-client-10

services:
  - postgresql

install:
  - pip install tox\>=2.1 tox-travis codecov

script:
  - tox
