---
  - name: Install base debian packages
    apt: name={{ item }} update_cache=yes state=present
    with_items:
      - binutils
      - build-essential
      - ccrypt
      - daemontools
      - ntp
      - git
      - openssh-client
      - openssh-server
