  - name: Install Postgres 9.6 apt repository
    apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
      state: present

  - name: Add PostgreSQL repository key
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: Install Postgres packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - libproj-dev
      - libpq-dev
      - python3-pip
      - postgresql-9.6
      - postgresql-client-9.6
      - postgresql-server-dev-9.6
      - postgresql-contrib-9.6
      - python3-dev
      - python3-psycopg2

  - name: Add PostgreSQL operating system group
    group: name=postgres state=present

  - name: Add PostgreSQL operating system user
    user: name=postgres comment="PostgreSQL binaries owner" group=postgres

  - name: Copy the configuration files
    copy:
      src: "{{ item }}"
      dest: /etc/postgresql/9.6/main/
      owner: postgres
      group: postgres
      mode: 0644
    with_items:
      - templates/9.6/main/pg_ctl.conf
      - templates/9.6/main/pg_hba.conf
      - templates/9.6/main/pg_ident.conf
      - templates/9.6/main/postgresql.conf
      - templates/9.6/main/start.conf
    notify: restart postgresql
