---

  - name: Install Postgres 9.6 apt repository
    apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
      state: present

  - name: Add PostgreSQL repository key
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

  - name: Install Postgres packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - libproj-dev
      - libpq-dev
      - python3-pip
      - postgresql-9.6
      - postgresql-client-9.6
      - postgresql-server-dev-9.6
      - postgresql-contrib-9.6
      - python3-dev
      - python3-psycopg2

  - name: Add PostgreSQL operating system group
    group: name=postgres state=present

  - name: Add PostgreSQL operating system user
    user: name=postgres comment="PostgreSQL binaries owner" group=postgres
