---

  site_name: "worldinfilms"
  virtualenv: "/var/uwsgi/apps/{{ site_name }}/venv"
  app_root: "/var/uwsgi/apps/{{ site_name }}/website"
  app_socket: "/var/uwsgi/{{ site_name }}.sock"
  app_pid: "/tmp/{{ site_name }}.pid"
  app_reload: "/tmp/{{ site_name }}.reload"
  app_log: "/var/log/uwsgi/app/{{ site_name }}.log"
  stats_socket: "/tmp/{{ site_name }}_stats.sock"
