  - name: Create /var/uwsgi/apps folder
    file:
      path: /var/uwsgi/apps
      owner: worldinfilms
      group: worldinfilms
      state: directory
      mode: 0755

  - name: Initial clone
    git:
      repo: "git@github.com:atombrella/worldinfilms.git"
      dest: "/var/uwsgi/apps/worldinfilms"
      version: master
      accept_hostkey: yes
      key_file: /home/worldinfilms/.ssh/id_rsa
    tags: once
    become_user: worldinfilms
    run_once: true

  - block:
    - name: Pull git
      git:
        repo={{ project_repo }}
        dest={{ project_root}}
        accept_hostkey=yes
        key_file=/home/worldinfilms/.ssh/id_rsa
      become_user: worldinfilms

    - name: Create virtualenv
      command:
        virtualenv --python=python3 venv
        chdir={{ project_root }}
        creates={{ virtualenv }}
      become_user: worldinfilms

    - name: Install newest version of pip in virtualenv
      pip:
        name=pip
        virtualenv={{ virtualenv }}
        state=forcereinstall
      become_user: worldinfilms

    - name: Install pip requirements
      pip:
        requirements="{{ project_root }}/requirements/base.txt"
        virtualenv="{{ virtualenv }}"
        virtualenv_python=python3.5
      become_user: worldinfilms

    - name: Copy over production settings
      template:
        src: production.py
        dest: /var/uwsgi/apps/worldinfilms/website/website/settings
        owner: www-data
        group: www-data
        mode: 0644
      become_user: worldinfilms

    - name: Migrate database
      django_manage:
        command=migrate
        app_path="{{ project_root }}/website/"
        virtualenv="{{ virtualenv }}"
        settings="website.settings.production"
      become_user: worldinfilms

    - name: create static files
      django_manage:
        command=collectstatic
        app_path="{{ project_root }}/website/"
        virtualenv="{{ virtualenv }}"
        settings="website.settings.production"
      become_user: worldinfilms
