---
  - name: Remove symlink in /etc/uwsgi/apps-available
    file: src=/etc/uwsgi/apps-available/{{ site_name }}.ini
      dest=/etc/uwsgi/apps-enabled/{{ site_name }}.ini
      state=absent

  - name: Install UWSGI package
    apt: name={{ item }} update_cache=yes
    with_items:
      - python3-virtualenv
      - uwsgi
      - uwsgi-plugin-python

  - name: Copy over uwsgi params
    copy: src=uwsgi/uwsgi_params dest=/etc/uwsgi/

  - name: Create reload files
    file: path=/tmp/all.reload group=worldinfilms owner=worldinfilms state=touch

  - name: Create reload files
    file: path=/tmp/{{ site_name }}.reload group=worldinfilms owner=worldinfilms state=touch

  - name: Create /var/uwsgi folder
    file: path=/var/uwsgi owner=worldinfilms group=worldinfilms state=directory mode=0755

  - name: Create /var/uwsgi/apps folder
    file: path=/var/uwsgi/apps owner=worldinfilms group=worldinfilms state=directory mode=0755

  - name: Set owner and permissions on /var/log/uwsgi/
    file: path=/var/log/uwsgi/ mode=0775 owner=worldinfilms group=worldinfilms recurse=yes

  - name: Set owner and permissions on /tmp/{{ site_name }}.pid
    file: path=/tmp/{{ site_name }}.pid owner=worldinfilms group=worldinfilms
    ignore_errors: yes

  - name: Set owner and permissions on /var/uwsgi/
    file: path=/var/uwsgi/ mode=0775 owner=worldinfilms group=worldinfilms

  - name: Set owner and permissions on /var/uwsgi/apps/
    file: path=/var/uwsgi/apps/ owner=worldinfilms group=worldinfilms recurse=yes
