---
  - name: Install UWSGI package
    apt: name={{ item }} update_cache=yes
    with_items:
      - python3-virtualenv
      - uwsgi
      - uwsgi-plugin-python
      - uwsgi-plugin-python3
      - memcached

  - name: Copy over uwsgi params
    copy: src=uwsgi/uwsgi_params dest=/etc/uwsgi/uwsgi_params

  - name: create emperor.ini file
    copy: src=etc/uwsgi/emperor.ini dest=/etc/uwsgi/emperor.ini owner=www-data group=www-data

  - name: Create reload files
    file: path=/tmp/all.reload group=www-data owner=www-data state=touch
    ignore_errors: true

  - name: Create reload files
    file: path=/tmp/worldinfilms.reload group=www-data owner=www-data state=touch

  - name: Create /var/uwsgi folder
    file: path=/var/uwsgi owner=worldinfilms group=worldinfilms state=directory mode=0755

  - name: Set owner and permissions on /tmp/worldinfilms.pid
    file: path=/tmp/worldinfilms.pid mode=0644 owner=worldinfilms group=worldinfilms
    ignore_errors: yes

  - name: Set owner and permissions on /var/uwsgi/
    file: path=/var/uwsgi/ mode=0775 owner=www-data group=www-data

  - name: Create /var/log/uwsgi directory
    file: path=/var/log/uwsgi state=directory mode=0644 owner=www-data group=www-data

  - name: copy over systemd configuration
    copy:
      src: lib/systemd/system/uwsgi.service
      dest: /lib/systemd/system/uwsgi.service
      owner: root
      group: root
      mode: 0644
    notify:
      - systemd daemon-reload
