---
  - name: Install UWSGI package
    apt: name={{ item }} update_cache=yes
    with_items:
      - python3-virtualenv
      - uwsgi
      - uwsgi-plugin-python
      - uwsgi-plugin-python3
      - memcached

  - name: Copy over uwsgi params
    copy: src=uwsgi/uwsgi_params dest=/etc/uwsgi/uwsgi_params

  - name: create emperor.ini file
    copy: src=etc/uwsgi/emperor.ini dest=/etc/uwsgi/emperor.ini owner=www-data group=www-data

  - name: Create the reload-file directory
    file: path=/var/uwsgi/reload-files state=directory owner=www-data group=www-data mode=0755

  - name: Create the reload file
    file:
      path=/var/uwsgi/reload-files/worldinfilms.reload
      state=touch
      mode=0644
      group=www-data
      owner=www-data

  - name: Create /var/uwsgi folder
    file: path=/var/uwsgi owner=www-data group=www-data state=directory mode=0755

  - name: Set owner and permissions on /var/uwsgi/
    file: path=/var/uwsgi/ mode=0775 owner=www-data group=www-data

  - name: Create /var/log/uwsgi directory
    file: path=/var/log/uwsgi state=directory mode=0644 owner=www-data group=www-data

  - name: copy over systemd configuration
    copy:
      src: lib/systemd/system/uwsgi.service
      dest: /lib/systemd/system/uwsgi.service
      owner: root
      group: root
      mode: 0644
    notify:
      - systemd daemon-reload
