---
  - name: Install UWSGI package
    apt: name={{ item }} update_cache=yes
    with_items:
      - python3-virtualenv
      - uwsgi
      - uwsgi-plugin-python
      - uwsgi-plugin-python3
      - memcached

  - name: Copy over uwsgi params
    copy: src=uwsgi/uwsgi_params dest=/etc/uwsgi/uwsgi_params

  - name: create emperor.ini file
    copy: src=etc/uwsgi/emperor.ini dest=/etc/uwsgi/emperor.ini owner=www-data group=www-data

  - name: Create reload files
    file: path=/tmp/all.reload group=www-data owner=www-data state=touch
    ignore_errors: true

  - name: Create reload files
    file: path=/tmp/worldinfilms.reload group=www-data owner=www-data state=touch

  - name: Create /var/uwsgi folder
    file: path=/var/uwsgi owner=worldinfilms group=worldinfilms state=directory mode=0755

  - name: Set owner and permissions on /tmp/{{ site_name }}.pid
    file: path=/tmp/{{ site_name }}.pid owner=worldinfilms group=worldinfilms
    ignore_errors: yes

  - name: Set owner and permissions on /var/uwsgi/
    file: path=/var/uwsgi/ mode=0775 owner=www-data group=www-data

  - name: Create uwsgi.conf file
    copy: src=etc/init/uwsgi.conf dest=/etc/init/uwsgi.conf owner=www-data group=www-data

  - name: Create socket directory
    file: src=/var/log/uwsgi/ mode=0644 state=directory

  - name: Create /var/log/uwsgi directory
    file: state=directory mode=0644
