---
  - name: Installs nginx web server
    apt: pkg=nginx state=present update_cache=true
    notify:
      - start nginx

  - name: Remove index.html for host
    file: path=/usr/share/nginx/html/index.nginx-debian.html state=absent

  - name: Create nginx include directory
    file: path=/etc/nginx/includes state=directory

  - name: Unactivate default site
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify:
      - reload nginx

  - name: Create configuration for HTTP
    template:
      src=templates/nginx/sites-available/{{ item }}
      dest=/etc/nginx/sites-available/{{ item }}
      mode=0644
      owner=www-data
      group=www-data
    with_items:
      - worldinfilms
      - ssl

  - name: Make symlink to sites-enabled
    file:
      src=/etc/nginx/sites-available/{{ item }}
      path=/etc/nginx/sites-enabled/{{ item }}
      state=link
      mode=0644
      owner=www-data
      group=www-data
    with_items:
      - worldinfilms
      - ssl
    notify:
      - reload nginx

  - name: Create nginx caching configuration
    copy:
      src=etc/nginx/conf.d/expires.conf
      dest=/etc/nginx/conf.d/expires.conf
      owner=www-data
      group=www-data
      mode=0644
    notify:
      - reload nginx

  - name: Create nginx.service file
    copy:
      src=lib/systemd/system/nginx.service
      dest=/lib/systemd/system/nginx.service
      owner=root
      group=root
      mode=0644
    notify:
      - systemd daemon-reload
      - restart nginx

  - name: Copy dhparam.pem over
    copy:
      src=etc/nginx/dhparam.pem
      dest=/etc/nginx/dhparam.pem
      owner=www-data
      group=www-data
    notify:
    - reload nginx

  - name: Copy nginx.conf file
    template: src=nginx/nginx.conf dest=/etc/nginx/nginx.conf mode=0644 owner=www-data group=www-data
    notify:
    - reload nginx
