# Generated by Django 2.0 on 2018-06-20 13:14

import blog.models
import django.core.validators
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180619_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=1024)),
                ('movie', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1900), django.core.validators.MaxValueValidator(limit_value=2050)])),
                ('imdb', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField((('main', wagtail.core.blocks.RichTextBlock(classname='full')), ('quote', blog.models.QuoteChooserBlock()), ('related', wagtail.core.blocks.PageChooserBlock(target_model=['blog.BlogPage'])), ('embedded_video', wagtail.embeds.blocks.EmbedBlock(icon='media')))),
        ),
    ]



