---

  - hosts: all
    vars:
      - domain_name: "worldinfilms.dk, www.worldinfilms.dk"
      - letsencrypt_cert_domains: "worldinfilms.dk, www.worldinfilms.dk"
    gather_facts: false
    roles:
      - letsencrypt
      - deploy
      - nginx
      - uwsgi
